BLUEPRINTS = [
        "libs/azure/functions/blueprints/azure/datalake/*",
        "libs/azure/functions/blueprints/azure/postgres/*",
        "libs/azure/functions/blueprints/azure/synapse/*",
        "libs/azure/functions/blueprints/esquire/audiences/builder/*",
        "libs/azure/functions/blueprints/esquire/audiences/meta/*",
        "libs/azure/functions/blueprints/esquire/audiences/utils/*",
        # "libs/azure/functions/blueprints/esquire/dashboard/meta/*",
        "libs/azure/functions/blueprints/meta/*",
        # "libs/azure/functions/blueprints/esquire/dashboard/oneview/*",
        # "libs/azure/functions/blueprints/keep_alive",
        "libs/azure/functions/blueprints/meta/*",
        # "libs/azure/functions/blueprints/oneview/reports/*",
        "libs/azure/functions/blueprints/onspot/*",
        "libs/azure/functions/blueprints/purge_instance_history",
        # "libs/azure/functions/blueprints/smarty/*",
        # "libs/azure/functions/blueprints/esquire/audiences/builder/*",
]