# File: libs/azure/functions/blueprints/esquire/dashboard/onspot/starter.py

from azure.durable_functions import (
    DurableOrchestrationClient,
    DurableOrchestrationContext,
    RetryOptions,
)
from azure.functions import HttpRequest
from libs.azure.functions import Blueprint
from datetime import datetime
from dateutil.relativedelta import relativedelta
import logging
import json
import os
import uuid

# Create a Blueprint instance
bp = Blueprint()


@bp.route(route="onspot_pull/starter", methods=["POST"])
@bp.durable_client_input(client_name="client")
async def starter_onspotPull(req: HttpRequest, client: DurableOrchestrationClient):
    params = json.loads(req.get_body())
    logging.warning(params)
    instance_id = await client.start_new("orchestrator_onspotPull", client_input={**params})

    return client.create_check_status_response(request=req, instance_id=instance_id)


@bp.orchestration_trigger(context_name="context")
def orchestrator_onspotPull(context: DurableOrchestrationContext):
    retry = RetryOptions(15000, 3)
    conn_str = "REPORTS_CONN_STR" if "REPORTS_CONN_STR" in os.environ.keys() else None
    container = "device-pulls"
    settings = context.get_input()

    # # now = datetime.utcnow()
    # # today = datetime(now.year, now.month, now.day)
    # start = datetime(2023, 7, 1)
    # end = datetime(2023, 12, 31)

    # with open(f"C:/Users/Owner/OneDrive - esquireadvertising.com/Ryan's Codebase/FSQ to OSM/Data/OSM_Walmarts_{settings['state']}.json") as f_in:
    #     geoframes = [(k, v) for k, v in json.load(f_in).items()]

    # batch_size = 100

    # # call onspot to get observations data (batched in groups of 100 locations)
    # yield context.task_all(
    #     [
    #         context.call_sub_orchestrator_with_retry(
    #             "onspot_orchestrator",
    #             retry,
    #             {
    #                 "conn_str": conn_str,
    #                 "container": f"{os.environ['TASK_HUB_NAME']}-largemessages",
    #                 "outputPath": f"{context.instance_id}/observations",
    #                 "endpoint": "/save/geoframe/all/observations",
    #                 "request": {
    #                     "type": "FeatureCollection",
    #                     "features": [
    #                         {
    #                             **value,
    #                             "properties": {
    #                                 "name": key,
    #                                 "fileName": key,
    #                                 "start": start.isoformat(),
    #                                 "end": end.isoformat(),
    #                                 "hash": False,
    #                                 "headers": [
    #                                     "deviceid",
    #                                     "timestamp",
    #                                     "lat",
    #                                     "lng",
    #                                 ],
    #                             },
    #                         }
    #                         for key, value in geoframes[i : i + batch_size]
    #                     ],
    #                 },
    #             },
    #             subinstance_id,
    #         )
    #         for i in range(0, len(geoframes), batch_size)
    #         if (subinstance_id := f"{context.instance_id}:observations:{i}")
    #     ]
    # )

    # # create temp CETAS to compress observations data into Parquet files
    # obs_urls = yield context.call_activity(
    #     "synapse_activity_cetas",
    #     {
    #         "instance_id": context.instance_id,
    #         "bind": "synapse-general",
    #         "table": {"name": "observations_temp"},
    #         "destination": {
    #             "conn_str": conn_str,
    #             "container": container,
    #             "handle": "sa_esquirereports",
    #             "path": f"walmarts/{context.instance_id}/observations",
    #             "format": "PARQUET_SNAPPY",
    #         },
    #         "query": cetas_query_observations_temp(context.instance_id),
    #         "return_urls": True,
    #     },
    # )

    # # create temp CETAS to identify unique deviceIDs
    # uid_urls = yield context.call_activity(
    #     "synapse_activity_cetas",
    #     {
    #         "instance_id": context.instance_id,
    #         "bind": "synapse-general",
    #         "table": {"name": "unique_deviceids_temp"},
    #         "destination": {
    #             "conn_str": conn_str,
    #             "container": f"{os.environ['TASK_HUB_NAME']}-largemessages",
    #             "handle": "sa_esquirereports",
    #             "path": f"{context.instance_id}/unique_deviceids",
    #             "format": "CSV",
    #         },
    #         "query": cetas_query_uniqueDeviceIds(context.instance_id),
    #         "return_urls": True,
    #     },
    # )

    # # call Onspot to get household demographics
    # yield context.task_all(
    #     [
    #         context.call_sub_orchestrator_with_retry(
    #             "onspot_orchestrator",
    #             retry,
    #             {
    #                 "conn_str": conn_str,
    #                 "container": f"{os.environ['TASK_HUB_NAME']}-largemessages",
    #                 "outputPath": f"{context.instance_id}/demographics",
    #                 "endpoint": "/save/files/demographics/all",
    #                 "request": {
    #                     "type": "FeatureCollection",
    #                     "features": [
    #                         {
    #                             "type": "Files",
    #                             "paths": [uid_urls[i].replace("https://", "az://")],
    #                             "properties": {"name": "demographics", "hash": False},
    #                         }
    #                     ],
    #                 },
    #             },
    #             subinstance_id,
    #         )
    #         for i in range(0, len(uid_urls), 1)
    #         if (subinstance_id := f"{context.instance_id}:demographics:{i}")
    #     ]
    # )

    # # create temp CETAS to compress demographics data into Parquet files
    # demo_urls = yield context.call_activity(
    #     "synapse_activity_cetas",
    #     {
    #         "instance_id": context.instance_id,
    #         "bind": "synapse-general",
    #         "table": {"name": "demographics_temp"},
    #         "destination": {
    #             "conn_str": conn_str,
    #             "container": container,
    #             "handle": "sa_esquirereports",
    #             "path": f"walmarts/{context.instance_id}/demographics",
    #             "format": "PARQUET_SNAPPY",
    #         },
    #         "query": cetas_query_demographics_temp(context.instance_id),
    #         "return_urls": True,
    #     },
    # )

    # create a final CETAS table for observations data
    logging.warning(cetas_query_observations())
    yield context.call_activity(
        "synapse_activity_cetas",
        {
            "instance_id": context.instance_id,
            "bind": "synapse-general",
            "table": {"name": "walmart_observations"},
            "destination": {
                "conn_str": conn_str,
                "container": container,
                "handle": "sa_esquirereports",
                "path": f"walmarts_cetas/observations/{context.instance_id}",
                "format": "PARQUET_SNAPPY",
            },
            "query": cetas_query_observations(),
            "commit": True,
            "view": True,
        },
    )

    # # create a final CETAS table for demographics data
    # yield context.call_activity(
    #     "synapse_activity_cetas",
    #     {
    #         "instance_id": context.instance_id,
    #         "bind": "synapse-general",
    #         "table": {"name": "walmart_demographics"},
    #         "destination": {
    #             "conn_str": conn_str,
    #             "container": container,
    #             "handle": "sa_esquirereports",
    #             "path": f"walmarts_cetas/demographics/{context.instance_id}",
    #             "format": "PARQUET_SNAPPY",
    #         },
    #         "query": cetas_query_demographics(),
    #         "commit": True,
    #         "view": True,
    #     },
    # )

    # # Purge history related to this instance
    # yield context.call_sub_orchestrator(
    #     "purge_instance_history",
    #     {"instance_id": context.instance_id},
    # )

    logging.warning("All tasks finished!")


def cetas_query_observations_temp(instance_id:str):
    return f"""
        SELECT
            data.filepath(1) AS [fsq_id],
            [deviceid],
            [timestamp],
            [lat] AS [latitude],
            [lng] AS [longitude]
        FROM OPENROWSET(
            BULK '{os.environ['TASK_HUB_NAME']}-largemessages/{instance_id}/observations/*',
            DATA_SOURCE = 'sa_esquirereports',
            FORMAT = 'CSV',
            PARSER_VERSION = '2.0',
            HEADER_ROW = TRUE
        ) WITH (
            [deviceid] VARCHAR(64),
            [timestamp] BIGINT,
            [lat] DECIMAL(11,6),
            [lng] DECIMAL(11,6)
        ) AS [data]
    """

def cetas_query_uniqueDeviceIds(instance_id:str):
    return f"""
        SELECT DISTINCT [deviceid]
        FROM OPENROWSET(
            BULK 'device-pulls/walmarts/{instance_id}/observations/*',
            DATA_SOURCE = 'sa_esquirereports',
            FORMAT = 'PARQUET'
        ) AS [data]
    """

def cetas_query_observations():
    return f"""
        SELECT
            [instance_id],
            [fsq_id],
            [deviceid],
            [timestamp],
            [latitude],
            [longitude]
        FROM OPENROWSET(
            BULK 'device-pulls/walmarts/*/observations/*',
            DATA_SOURCE = 'sa_esquirereports',
            FORMAT = 'PARQUET'
        ) WITH (
            [instance_id] VARCHAR(36) COLLATE Latin1_General_100_BIN2_UTF8,
            [fsq_id] VARCHAR(36) COLLATE Latin1_General_100_BIN2_UTF8,
            [deviceid] VARCHAR(64) COLLATE Latin1_General_100_BIN2_UTF8,
            [timestamp] BIGINT,
            [latitude] DECIMAL(11,6),
            [longitude] DECIMAL(11,6)
        ) AS [data]
    """

def cetas_query_demographics_temp(instance_id:str):
    return f"""
        SELECT
            [hashed device id] AS [deviceid],
            [state],
            [city],
            [zip],
            [zip4],
            [cbmsa_name],
            [msa_name],
            [fips_name],
            [male],
            [female],
            [married],
            [dwelling_type apt/multi-family],
            [dwelling_type single family],
            [completed high school],
            [some college],
            [completed college],
            [completed graduate school],
            [attended vocational/technical school],
            [household_income under $15000],
            [household_income $15000 - $24999],
            [household_income $25000 - $34999],
            [household_income $35000 - $49999],
            [household_income $50000 - $74999],
            [household_income $75000 - $99999],
            [household_income $100000 - $149999],
            [household_income $150000 - $159999],
            [household_income $160000 - $164999],
            [household_income $165000 - $199999],
            [household_income $200000 - $249999],
            [household_income $250000+],
            [household_size],
            [home_owner],
            [networth less than $50000],
            [networth $50000 - $99999],
            [networth $100000 - $249999],
            [networth $250000 - $499999],
            [networth $500000+],
            [presence_of_children],
            [presence_of_single_adult],
            [presence_of_young_adult],
            [presence_of_senior_adult],
            [presence_of_veteran],
            [estimated_age 18-24],
            [estimated_age 25-29],
            [estimated_age 30-34],
            [estimated_age 35-39],
            [estimated_age 40-44],
            [estimated_age 45-49],
            [estimated_age 50-54],
            [estimated_age 55-59],
            [estimated_age 60-64],
            [estimated_age 65-69],
            [estimated_age 70+],
            [buyer_men_apparel],
            [buyer_big_and_tall_men_apparel],
            [buyer_women_apparel],
            [buyer_petite_women_apparel],
            [buyer_plus_women_apparel],
            [buyer_young_women_apparel],
            [buyer_audio_books_and_music],
            [buyer_auto],
            [buyer_cosmetic_products],
            [buyer_books_and_magazines],
            [buyer_children_products],
            [buyer_gardening_products],
            [buyer_health_and_beauty_products],
            [buyer_hunting_and_shooting],
            [buyer_jewelry],
            [buyer_photography],
            [buyer_sports],
            [interest_arts],
            [interest_arts_antiques],
            [interest_auto],
            [interest_collector],
            [interest_board_games],
            [interest_sailing],
            [interest_camping],
            [interest_cat],
            [interest_children],
            [interest_antiques],
            [interest_coins],
            [interest_collectibles],
            [interest_military],
            [interest_sports],
            [interest_stamps],
            [interest_art_collectibles],
            [interest_cooking],
            [interest_gourmet_cooking],
            [interest_crafts],
            [interest_cruise],
            [interest_diet],
            [interest_dog],
            [interest_domestic_travel],
            [interest_education],
            [interest_aerobic],
            [interest_running],
            [interest_walking],
            [interest_fishing],
            [interest_food_wines],
            [interest_gambling],
            [interest_golf],
            [interest_health_medical],
            [interest_home_gardening],
            [interest_home_furnishings],
            [interest_home_improvement],
            [interest_hunting],
            [interest_grandchildren],
            [interest_parenting],
            [interest_pets],
            [interest_international_travel],
            [interest_equestrian],
            [interest_motorcycling],
            [interest_musical_instruments],
            [interest_nascar],
            [interest_natural_foods],
            [interest_photography],
            [interest_scuba_diving],
            [interest_self_improvement],
            [interest_snow_skiing],
            [interest_tennis],
            [interest_travel],
            [interest_woodworking],
            [reading_audio_books],
            [reading_current_affairs],
            [reading_financial],
            [reading_history],
            [reading_magazines],
            [reading_general],
            [reading_religious],
            [reading_space],
            [reading_science_fiction],
            [reading_religious_material],
            [entertain_gaming],
            [entertain_dvds],
            [entertain_tv_movies],
            [entertain_computers],
            [entertain_pc_games],
            [entertain_music_home_stereo],
            [entertain_music_player],
            [entertain_music_listener],
            [entertain_movies],
            [entertain_tv],
            [entertain_videos_games],
            [entertain_satellite],
            [entertain_theater],
            [entertain_music],
            [donor_contribution],
            [donor_animal],
            [donor_arts],
            [donor_children],
            [donor_wildlife],
            [donor_environment],
            [donor_health],
            [donor_international_aid],
            [donor_community],
            [donor_religious],
            [donor_veteran],
            [spectator_auto],
            [spectator_sports_tv],
            [spectator_football],
            [spectator_baseball],
            [spectator_basketball],
            [spectator_hockey],
            [spectator_soccer],
            [ethnicity_algerian],
            [ehtnicity_angolan],
            [ethnicity_black_african],
            [ethnicity_botswanian],
            [ethnicity_burkina_faso],
            [ethnicity_cameroonian],
            [ethnicity_central_african_republic],
            [ethnicity_chadian],
            [ethnicity_congolese],
            [ethnicity_ethiopian],
            [ethnicity_gabon],
            [ethnicity_gambian],
            [ethnicity_ghanaian],
            [ethnicity_guinean],
            [ehtnicity_hausa],
            [ethnicity_ivorian],
            [ethnicity_kenyan],
            [ethnicity_liberian],
            [ethnicity_libyan],
            [ethnicity_madagascan],
            [ethnicity_mozambican],
            [ethnicity_moroccan],
            [ethnicity_nigerian],
            [ethnicity_rwandan],
            [ethnicity_senegalese],
            [ethnicity_sierre_leone],
            [ethnicity_somalain],
            [ethnicity_sudanese],
            [ethnicity_swaziland],
            [ethnicity_ugandan],
            [ethnicity_zairean],
            [ethnicity_zambian],
            [ethnicity_zimbabwean],
            [ethnicity_zulu],
            [ethnicity_african_american],
            [ethnicity_caribbean_african_american],
            [ethnicity_american_indian],
            [ethnicity_bangladesh],
            [ethnicity_chinese],
            [ethnicity_korean],
            [ethnicity_japanese],
            [ethnicity_myanmar],
            [ethnicity_pakistani],
            [ethnicity_philippine],
            [ethnicity_thai],
            [ethnicity_tibetan],
            [ethnicity_vietnamese],
            [ethnicity_other_asian],
            [ethnicity_albanian],
            [ethnicity_austrian],
            [ethnicity_basque],
            [ethnicity_belgian],
            [ethnicity_belorussian],
            [ethnicity_bulgarian],
            [ethnicity_croatian],
            [ethnicity_czech],
            [ethnicity_danish],
            [ethnicity_dutch],
            [ethnicity_estonian],
            [ethnicity_finnish],
            [ethnicity_french],
            [ethnicity_georgian],
            [ethnicity_german],
            [ethnicity_greek],
            [ethnicity_hungarian],
            [ethnicity_italian],
            [ethnicity_latvian],
            [ethnicity_lithuanian],
            [ethnicity_luxembourgian],
            [ethnicity_polish],
            [ethnicity_portuguese],
            [ethnicity_romanian],
            [ethnicity_russian],
            [ethnicity_serbian],
            [ethnicity_swedish],
            [ethnicity_swiss],
            [ehtnicity_ukrainian],
            [ethnicity_maltese],
            [ethnicity_english],
            [ethnicity_irish],
            [ethnicity_welsh],
            [ethnicity_scottish],
            [ethnicity_hispanic],
            [ethnicity_arabic],
            [ethnicity_armenian],
            [ethnicity_afghan],
            [ethnicity_azerbaijani],
            [ethnicity_egyptian],
            [ethnicity_iraqi],
            [ethnicity_kazakhstan],
            [ethnicity_kirghizia],
            [ethnicity_kurdish],
            [ethnicity_kuwaiti],
            [ethnicity_persian],
            [ethnicity_qatari],
            [ethnicity_saudi],
            [ethnicity_turkish],
            [ethnicity_bosnian_muslim],
            [ethnicity_hindu],
            [ethnicity_jewish],
            [ethnicity_australian],
            [ethnicity_hawaiian],
            [ethnicity_indonesian],
            [ethnicity_maldivian_tongan],
            [ethnicity_new_zealand],
            [ethnicity_papua_new_guinean],
            [ethnicity_seychelles],
            [ethnicity_sinhalese_sri_lankan],
            [ethnicity_western_samoan],
            [home_value under $50000],
            [home_value $50000 - $99999],
            [home_value $100000 - $149999],
            [home_value $150000 - $199999],
            [home_value $200000 - $249999],
            [home_value $250000 - $299999],
            [home_value $300000 - $349999],
            [home_value $350000 - $399999],
            [home_value $400000 - $449999],
            [home_value $450000 - $499999],
            [home_value $500000 - $749999],
            [home_value $750000 - $999999],
            [home_value $1 million+],
            [mortgage community development authority],
            [mortgage conventional],
            [mortgage fha],
            [mortgage private party leader],
            [mortgage small business administration],
            [mortgage va],
            [mortgage wrap-around mortgage],
            [has_credit],
            [credit_card_gas],
            [credit_card_high_limit],
            [credit_card_standard],
            [credit_card_rewards],
            [occupation doctor],
            [occupation farming/agriculture],
            [occupation financial services],
            [occupation middle_management],
            [occupation office_clerical],
            [occupation professional/technical],
            [occupation retired],
            [occupation sales/marketing],
            [occupation skilled_trade],
            [occupation student],
            [occupation teacher/educator],
            [occupation accountant],
            [occupation business_owner],
            [occupation contractor],
            [occupation self_employed]
        FROM OPENROWSET(
            BULK '{os.environ['TASK_HUB_NAME']}-largemessages/{instance_id}/demographics/*',
            DATA_SOURCE = 'sa_esquirereports',
            FORMAT = 'CSV',
            PARSER_VERSION = '2.0',
            HEADER_ROW = TRUE
        ) WITH (
            [location (venue)] VARCHAR(256),
            [state] VARCHAR(2),
            [city] VARCHAR(256),
            [zip] VARCHAR(5),
            [zip4] VARCHAR(4),
            [hashed device id] VARCHAR(80),
            [number of instances (count seen at location)] INT,
            [cbmsa_name] VARCHAR(256),
            [msa_name] VARCHAR(256),
            [fips_name] VARCHAR(256),
            [male] BIT,
            [female] BIT,
            [married] BIT,
            [dwelling_type apt/multi-family] BIT,
            [dwelling_type single family] BIT,
            [completed high school] BIT,
            [some college] BIT,
            [completed college] BIT,
            [completed graduate school] BIT,
            [attended vocational/technical school] BIT,
            [household_income under $15000] BIT,
            [household_income $15000 - $24999] BIT,
            [household_income $25000 - $34999] BIT,
            [household_income $35000 - $49999] BIT,
            [household_income $50000 - $74999] BIT,
            [household_income $75000 - $99999] BIT,
            [household_income $100000 - $149999] BIT,
            [household_income $150000 - $159999] BIT,
            [household_income $160000 - $164999] BIT,
            [household_income $165000 - $199999] BIT,
            [household_income $200000 - $249999] BIT,
            [household_income $250000+] BIT,
            [household_size] INT,
            [home_owner] BIT,
            [networth less than $50000] BIT,
            [networth $50000 - $99999] BIT,
            [networth $100000 - $249999] BIT,
            [networth $250000 - $499999] BIT,
            [networth $500000+] BIT,
            [presence_of_children] BIT,
            [presence_of_single_adult] BIT,
            [presence_of_young_adult] BIT,
            [presence_of_senior_adult] BIT,
            [presence_of_veteran] BIT,
            [estimated_age 18-24] BIT,
            [estimated_age 25-29] BIT,
            [estimated_age 30-34] BIT,
            [estimated_age 35-39] BIT,
            [estimated_age 40-44] BIT,
            [estimated_age 45-49] BIT,
            [estimated_age 50-54] BIT,
            [estimated_age 55-59] BIT,
            [estimated_age 60-64] BIT,
            [estimated_age 65-69] BIT,
            [estimated_age 70+] BIT,
            [buyer_men_apparel] BIT,
            [buyer_big_and_tall_men_apparel] BIT,
            [buyer_women_apparel] BIT,
            [buyer_petite_women_apparel] BIT,
            [buyer_plus_women_apparel] BIT,
            [buyer_young_women_apparel] BIT,
            [buyer_audio_books_and_music] BIT,
            [buyer_auto] BIT,
            [buyer_cosmetic_products] BIT,
            [buyer_books_and_magazines] BIT,
            [buyer_children_products] BIT,
            [buyer_gardening_products] BIT,
            [buyer_health_and_beauty_products] BIT,
            [buyer_hunting_and_shooting] BIT,
            [buyer_jewelry] BIT,
            [buyer_photography] BIT,
            [buyer_sports] BIT,
            [interest_arts] BIT,
            [interest_arts_antiques] BIT,
            [interest_auto] BIT,
            [interest_collector] BIT,
            [interest_board_games] BIT,
            [interest_sailing] BIT,
            [interest_camping] BIT,
            [interest_cat] BIT,
            [interest_children] BIT,
            [interest_antiques] BIT,
            [interest_coins] BIT,
            [interest_collectibles] BIT,
            [interest_military] BIT,
            [interest_sports] BIT,
            [interest_stamps] BIT,
            [interest_art_collectibles] BIT,
            [interest_cooking] BIT,
            [interest_gourmet_cooking] BIT,
            [interest_crafts] BIT,
            [interest_cruise] BIT,
            [interest_diet] BIT,
            [interest_dog] BIT,
            [interest_domestic_travel] BIT,
            [interest_education] BIT,
            [interest_aerobic] BIT,
            [interest_running] BIT,
            [interest_walking] BIT,
            [interest_fishing] BIT,
            [interest_food_wines] BIT,
            [interest_gambling] BIT,
            [interest_golf] BIT,
            [interest_health_medical] BIT,
            [interest_home_gardening] BIT,
            [interest_home_furnishings] BIT,
            [interest_home_improvement] BIT,
            [interest_hunting] BIT,
            [interest_grandchildren] BIT,
            [interest_parenting] BIT,
            [interest_pets] BIT,
            [interest_international_travel] BIT,
            [interest_equestrian] BIT,
            [interest_motorcycling] BIT,
            [interest_musical_instruments] BIT,
            [interest_nascar] BIT,
            [interest_natural_foods] BIT,
            [interest_photography] BIT,
            [interest_scuba_diving] BIT,
            [interest_self_improvement] BIT,
            [interest_snow_skiing] BIT,
            [interest_tennis] BIT,
            [interest_travel] BIT,
            [interest_woodworking] BIT,
            [reading_audio_books] BIT,
            [reading_current_affairs] BIT,
            [reading_financial] BIT,
            [reading_history] BIT,
            [reading_magazines] BIT,
            [reading_general] BIT,
            [reading_religious] BIT,
            [reading_space] BIT,
            [reading_science_fiction] BIT,
            [reading_religious_material] BIT,
            [entertain_gaming] BIT,
            [entertain_dvds] BIT,
            [entertain_tv_movies] BIT,
            [entertain_computers] BIT,
            [entertain_pc_games] BIT,
            [entertain_music_home_stereo] BIT,
            [entertain_music_player] BIT,
            [entertain_music_listener] BIT,
            [entertain_movies] BIT,
            [entertain_tv] BIT,
            [entertain_videos_games] BIT,
            [entertain_satellite] BIT,
            [entertain_theater] BIT,
            [entertain_music] BIT,
            [donor_contribution] BIT,
            [donor_animal] BIT,
            [donor_arts] BIT,
            [donor_children] BIT,
            [donor_wildlife] BIT,
            [donor_environment] BIT,
            [donor_health] BIT,
            [donor_international_aid] BIT,
            [donor_community] BIT,
            [donor_religious] BIT,
            [donor_veteran] BIT,
            [spectator_auto] BIT,
            [spectator_sports_tv] BIT,
            [spectator_football] BIT,
            [spectator_baseball] BIT,
            [spectator_basketball] BIT,
            [spectator_hockey] BIT,
            [spectator_soccer] BIT,
            [ethnicity_algerian] BIT,
            [ehtnicity_angolan] BIT,
            [ethnicity_black_african] BIT,
            [ethnicity_botswanian] BIT,
            [ethnicity_burkina_faso] BIT,
            [ethnicity_cameroonian] BIT,
            [ethnicity_central_african_republic] BIT,
            [ethnicity_chadian] BIT,
            [ethnicity_congolese] BIT,
            [ethnicity_ethiopian] BIT,
            [ethnicity_gabon] BIT,
            [ethnicity_gambian] BIT,
            [ethnicity_ghanaian] BIT,
            [ethnicity_guinean] BIT,
            [ehtnicity_hausa] BIT,
            [ethnicity_ivorian] BIT,
            [ethnicity_kenyan] BIT,
            [ethnicity_liberian] BIT,
            [ethnicity_libyan] BIT,
            [ethnicity_madagascan] BIT,
            [ethnicity_mozambican] BIT,
            [ethnicity_moroccan] BIT,
            [ethnicity_nigerian] BIT,
            [ethnicity_rwandan] BIT,
            [ethnicity_senegalese] BIT,
            [ethnicity_sierre_leone] BIT,
            [ethnicity_somalain] BIT,
            [ethnicity_sudanese] BIT,
            [ethnicity_swaziland] BIT,
            [ethnicity_ugandan] BIT,
            [ethnicity_zairean] BIT,
            [ethnicity_zambian] BIT,
            [ethnicity_zimbabwean] BIT,
            [ethnicity_zulu] BIT,
            [ethnicity_african_american] BIT,
            [ethnicity_caribbean_african_american] BIT,
            [ethnicity_american_indian] BIT,
            [ethnicity_bangladesh] BIT,
            [ethnicity_chinese] BIT,
            [ethnicity_korean] BIT,
            [ethnicity_japanese] BIT,
            [ethnicity_myanmar] BIT,
            [ethnicity_pakistani] BIT,
            [ethnicity_philippine] BIT,
            [ethnicity_thai] BIT,
            [ethnicity_tibetan] BIT,
            [ethnicity_vietnamese] BIT,
            [ethnicity_other_asian] BIT,
            [ethnicity_albanian] BIT,
            [ethnicity_austrian] BIT,
            [ethnicity_basque] BIT,
            [ethnicity_belgian] BIT,
            [ethnicity_belorussian] BIT,
            [ethnicity_bulgarian] BIT,
            [ethnicity_croatian] BIT,
            [ethnicity_czech] BIT,
            [ethnicity_danish] BIT,
            [ethnicity_dutch] BIT,
            [ethnicity_estonian] BIT,
            [ethnicity_finnish] BIT,
            [ethnicity_french] BIT,
            [ethnicity_georgian] BIT,
            [ethnicity_german] BIT,
            [ethnicity_greek] BIT,
            [ethnicity_hungarian] BIT,
            [ethnicity_italian] BIT,
            [ethnicity_latvian] BIT,
            [ethnicity_lithuanian] BIT,
            [ethnicity_luxembourgian] BIT,
            [ethnicity_polish] BIT,
            [ethnicity_portuguese] BIT,
            [ethnicity_romanian] BIT,
            [ethnicity_russian] BIT,
            [ethnicity_serbian] BIT,
            [ethnicity_swedish] BIT,
            [ethnicity_swiss] BIT,
            [ehtnicity_ukrainian] BIT,
            [ethnicity_maltese] BIT,
            [ethnicity_english] BIT,
            [ethnicity_irish] BIT,
            [ethnicity_welsh] BIT,
            [ethnicity_scottish] BIT,
            [ethnicity_hispanic] BIT,
            [ethnicity_arabic] BIT,
            [ethnicity_armenian] BIT,
            [ethnicity_afghan] BIT,
            [ethnicity_azerbaijani] BIT,
            [ethnicity_egyptian] BIT,
            [ethnicity_iraqi] BIT,
            [ethnicity_kazakhstan] BIT,
            [ethnicity_kirghizia] BIT,
            [ethnicity_kurdish] BIT,
            [ethnicity_kuwaiti] BIT,
            [ethnicity_persian] BIT,
            [ethnicity_qatari] BIT,
            [ethnicity_saudi] BIT,
            [ethnicity_turkish] BIT,
            [ethnicity_bosnian_muslim] BIT,
            [ethnicity_hindu] BIT,
            [ethnicity_jewish] BIT,
            [ethnicity_australian] BIT,
            [ethnicity_hawaiian] BIT,
            [ethnicity_indonesian] BIT,
            [ethnicity_maldivian_tongan] BIT,
            [ethnicity_new_zealand] BIT,
            [ethnicity_papua_new_guinean] BIT,
            [ethnicity_seychelles] BIT,
            [ethnicity_sinhalese_sri_lankan] BIT,
            [ethnicity_western_samoan] BIT,
            [home_value under $50000] BIT,
            [home_value $50000 - $99999] BIT,
            [home_value $100000 - $149999] BIT,
            [home_value $150000 - $199999] BIT,
            [home_value $200000 - $249999] BIT,
            [home_value $250000 - $299999] BIT,
            [home_value $300000 - $349999] BIT,
            [home_value $350000 - $399999] BIT,
            [home_value $400000 - $449999] BIT,
            [home_value $450000 - $499999] BIT,
            [home_value $500000 - $749999] BIT,
            [home_value $750000 - $999999] BIT,
            [home_value $1 million+] BIT,
            [mortgage community development authority] BIT,
            [mortgage conventional] BIT,
            [mortgage fha] BIT,
            [mortgage private party leader] BIT,
            [mortgage small business administration] BIT,
            [mortgage va] BIT,
            [mortgage wrap-around mortgage] BIT,
            [has_credit] BIT,
            [credit_card_gas] BIT,
            [credit_card_high_limit] BIT,
            [credit_card_standard] BIT,
            [credit_card_rewards] BIT,
            [occupation doctor] BIT,
            [occupation farming/agriculture] BIT,
            [occupation financial services] BIT,
            [occupation middle_management] BIT,
            [occupation office_clerical] BIT,
            [occupation professional/technical] BIT,
            [occupation retired] BIT,
            [occupation sales/marketing] BIT,
            [occupation skilled_trade] BIT,
            [occupation student] BIT,
            [occupation teacher/educator] BIT,
            [occupation accountant] BIT,
            [occupation business_owner] BIT,
            [occupation contractor] BIT,
            [occupation self_employed] BIT
        ) AS [data]
    """


def cetas_query_demographics():
    return f"""
        SELECT
            [deviceid],
            [state],
            [city],
            [zip],
            [zip4],
            [cbmsa_name],
            [msa_name],
            [fips_name],
            [male],
            [female],
            [married],
            [dwelling_type apt/multi-family],
            [dwelling_type single family],
            [completed high school],
            [some college],
            [completed college],
            [completed graduate school],
            [attended vocational/technical school],
            [household_income under $15000],
            [household_income $15000 - $24999],
            [household_income $25000 - $34999],
            [household_income $35000 - $49999],
            [household_income $50000 - $74999],
            [household_income $75000 - $99999],
            [household_income $100000 - $149999],
            [household_income $150000 - $159999],
            [household_income $160000 - $164999],
            [household_income $165000 - $199999],
            [household_income $200000 - $249999],
            [household_income $250000+],
            [household_size],
            [home_owner],
            [networth less than $50000],
            [networth $50000 - $99999],
            [networth $100000 - $249999],
            [networth $250000 - $499999],
            [networth $500000+],
            [presence_of_children],
            [presence_of_single_adult],
            [presence_of_young_adult],
            [presence_of_senior_adult],
            [presence_of_veteran],
            [estimated_age 18-24],
            [estimated_age 25-29],
            [estimated_age 30-34],
            [estimated_age 35-39],
            [estimated_age 40-44],
            [estimated_age 45-49],
            [estimated_age 50-54],
            [estimated_age 55-59],
            [estimated_age 60-64],
            [estimated_age 65-69],
            [estimated_age 70+],
            [buyer_men_apparel],
            [buyer_big_and_tall_men_apparel],
            [buyer_women_apparel],
            [buyer_petite_women_apparel],
            [buyer_plus_women_apparel],
            [buyer_young_women_apparel],
            [buyer_audio_books_and_music],
            [buyer_auto],
            [buyer_cosmetic_products],
            [buyer_books_and_magazines],
            [buyer_children_products],
            [buyer_gardening_products],
            [buyer_health_and_beauty_products],
            [buyer_hunting_and_shooting],
            [buyer_jewelry],
            [buyer_photography],
            [buyer_sports],
            [interest_arts],
            [interest_arts_antiques],
            [interest_auto],
            [interest_collector],
            [interest_board_games],
            [interest_sailing],
            [interest_camping],
            [interest_cat],
            [interest_children],
            [interest_antiques],
            [interest_coins],
            [interest_collectibles],
            [interest_military],
            [interest_sports],
            [interest_stamps],
            [interest_art_collectibles],
            [interest_cooking],
            [interest_gourmet_cooking],
            [interest_crafts],
            [interest_cruise],
            [interest_diet],
            [interest_dog],
            [interest_domestic_travel],
            [interest_education],
            [interest_aerobic],
            [interest_running],
            [interest_walking],
            [interest_fishing],
            [interest_food_wines],
            [interest_gambling],
            [interest_golf],
            [interest_health_medical],
            [interest_home_gardening],
            [interest_home_furnishings],
            [interest_home_improvement],
            [interest_hunting],
            [interest_grandchildren],
            [interest_parenting],
            [interest_pets],
            [interest_international_travel],
            [interest_equestrian],
            [interest_motorcycling],
            [interest_musical_instruments],
            [interest_nascar],
            [interest_natural_foods],
            [interest_photography],
            [interest_scuba_diving],
            [interest_self_improvement],
            [interest_snow_skiing],
            [interest_tennis],
            [interest_travel],
            [interest_woodworking],
            [reading_audio_books],
            [reading_current_affairs],
            [reading_financial],
            [reading_history],
            [reading_magazines],
            [reading_general],
            [reading_religious],
            [reading_space],
            [reading_science_fiction],
            [reading_religious_material],
            [entertain_gaming],
            [entertain_dvds],
            [entertain_tv_movies],
            [entertain_computers],
            [entertain_pc_games],
            [entertain_music_home_stereo],
            [entertain_music_player],
            [entertain_music_listener],
            [entertain_movies],
            [entertain_tv],
            [entertain_videos_games],
            [entertain_satellite],
            [entertain_theater],
            [entertain_music],
            [donor_contribution],
            [donor_animal],
            [donor_arts],
            [donor_children],
            [donor_wildlife],
            [donor_environment],
            [donor_health],
            [donor_international_aid],
            [donor_community],
            [donor_religious],
            [donor_veteran],
            [spectator_auto],
            [spectator_sports_tv],
            [spectator_football],
            [spectator_baseball],
            [spectator_basketball],
            [spectator_hockey],
            [spectator_soccer],
            [ethnicity_algerian],
            [ehtnicity_angolan],
            [ethnicity_black_african],
            [ethnicity_botswanian],
            [ethnicity_burkina_faso],
            [ethnicity_cameroonian],
            [ethnicity_central_african_republic],
            [ethnicity_chadian],
            [ethnicity_congolese],
            [ethnicity_ethiopian],
            [ethnicity_gabon],
            [ethnicity_gambian],
            [ethnicity_ghanaian],
            [ethnicity_guinean],
            [ehtnicity_hausa],
            [ethnicity_ivorian],
            [ethnicity_kenyan],
            [ethnicity_liberian],
            [ethnicity_libyan],
            [ethnicity_madagascan],
            [ethnicity_mozambican],
            [ethnicity_moroccan],
            [ethnicity_nigerian],
            [ethnicity_rwandan],
            [ethnicity_senegalese],
            [ethnicity_sierre_leone],
            [ethnicity_somalain],
            [ethnicity_sudanese],
            [ethnicity_swaziland],
            [ethnicity_ugandan],
            [ethnicity_zairean],
            [ethnicity_zambian],
            [ethnicity_zimbabwean],
            [ethnicity_zulu],
            [ethnicity_african_american],
            [ethnicity_caribbean_african_american],
            [ethnicity_american_indian],
            [ethnicity_bangladesh],
            [ethnicity_chinese],
            [ethnicity_korean],
            [ethnicity_japanese],
            [ethnicity_myanmar],
            [ethnicity_pakistani],
            [ethnicity_philippine],
            [ethnicity_thai],
            [ethnicity_tibetan],
            [ethnicity_vietnamese],
            [ethnicity_other_asian],
            [ethnicity_albanian],
            [ethnicity_austrian],
            [ethnicity_basque],
            [ethnicity_belgian],
            [ethnicity_belorussian],
            [ethnicity_bulgarian],
            [ethnicity_croatian],
            [ethnicity_czech],
            [ethnicity_danish],
            [ethnicity_dutch],
            [ethnicity_estonian],
            [ethnicity_finnish],
            [ethnicity_french],
            [ethnicity_georgian],
            [ethnicity_german],
            [ethnicity_greek],
            [ethnicity_hungarian],
            [ethnicity_italian],
            [ethnicity_latvian],
            [ethnicity_lithuanian],
            [ethnicity_luxembourgian],
            [ethnicity_polish],
            [ethnicity_portuguese],
            [ethnicity_romanian],
            [ethnicity_russian],
            [ethnicity_serbian],
            [ethnicity_swedish],
            [ethnicity_swiss],
            [ehtnicity_ukrainian],
            [ethnicity_maltese],
            [ethnicity_english],
            [ethnicity_irish],
            [ethnicity_welsh],
            [ethnicity_scottish],
            [ethnicity_hispanic],
            [ethnicity_arabic],
            [ethnicity_armenian],
            [ethnicity_afghan],
            [ethnicity_azerbaijani],
            [ethnicity_egyptian],
            [ethnicity_iraqi],
            [ethnicity_kazakhstan],
            [ethnicity_kirghizia],
            [ethnicity_kurdish],
            [ethnicity_kuwaiti],
            [ethnicity_persian],
            [ethnicity_qatari],
            [ethnicity_saudi],
            [ethnicity_turkish],
            [ethnicity_bosnian_muslim],
            [ethnicity_hindu],
            [ethnicity_jewish],
            [ethnicity_australian],
            [ethnicity_hawaiian],
            [ethnicity_indonesian],
            [ethnicity_maldivian_tongan],
            [ethnicity_new_zealand],
            [ethnicity_papua_new_guinean],
            [ethnicity_seychelles],
            [ethnicity_sinhalese_sri_lankan],
            [ethnicity_western_samoan],
            [home_value under $50000],
            [home_value $50000 - $99999],
            [home_value $100000 - $149999],
            [home_value $150000 - $199999],
            [home_value $200000 - $249999],
            [home_value $250000 - $299999],
            [home_value $300000 - $349999],
            [home_value $350000 - $399999],
            [home_value $400000 - $449999],
            [home_value $450000 - $499999],
            [home_value $500000 - $749999],
            [home_value $750000 - $999999],
            [home_value $1 million+],
            [mortgage community development authority],
            [mortgage conventional],
            [mortgage fha],
            [mortgage private party leader],
            [mortgage small business administration],
            [mortgage va],
            [mortgage wrap-around mortgage],
            [has_credit],
            [credit_card_gas],
            [credit_card_high_limit],
            [credit_card_standard],
            [credit_card_rewards],
            [occupation doctor],
            [occupation farming/agriculture],
            [occupation financial services],
            [occupation middle_management],
            [occupation office_clerical],
            [occupation professional/technical],
            [occupation retired],
            [occupation sales/marketing],
            [occupation skilled_trade],
            [occupation student],
            [occupation teacher/educator],
            [occupation accountant],
            [occupation business_owner],
            [occupation contractor],
            [occupation self_employed]
        FROM OPENROWSET(
            BULK 'device-pulls/walmarts/*/demographics/*',
            DATA_SOURCE = 'sa_esquirereports',
            FORMAT = 'PARQUET'
        ) WITH (
            [location (venue)] VARCHAR(256) COLLATE Latin1_General_100_BIN2_UTF8,
            [state] VARCHAR(2) COLLATE Latin1_General_100_BIN2_UTF8,
            [city] VARCHAR(256) COLLATE Latin1_General_100_BIN2_UTF8,
            [zip] VARCHAR(5) COLLATE Latin1_General_100_BIN2_UTF8,
            [zip4] VARCHAR(4) COLLATE Latin1_General_100_BIN2_UTF8,
            [deviceid] VARCHAR(80) COLLATE Latin1_General_100_BIN2_UTF8,
            [number of instances (count seen at location)] INT,
            [cbmsa_name] VARCHAR(256) COLLATE Latin1_General_100_BIN2_UTF8,
            [msa_name] VARCHAR(256) COLLATE Latin1_General_100_BIN2_UTF8,
            [fips_name] VARCHAR(256) COLLATE Latin1_General_100_BIN2_UTF8,
            [male] BIT,
            [female] BIT,
            [married] BIT,
            [dwelling_type apt/multi-family] BIT,
            [dwelling_type single family] BIT,
            [completed high school] BIT,
            [some college] BIT,
            [completed college] BIT,
            [completed graduate school] BIT,
            [attended vocational/technical school] BIT,
            [household_income under $15000] BIT,
            [household_income $15000 - $24999] BIT,
            [household_income $25000 - $34999] BIT,
            [household_income $35000 - $49999] BIT,
            [household_income $50000 - $74999] BIT,
            [household_income $75000 - $99999] BIT,
            [household_income $100000 - $149999] BIT,
            [household_income $150000 - $159999] BIT,
            [household_income $160000 - $164999] BIT,
            [household_income $165000 - $199999] BIT,
            [household_income $200000 - $249999] BIT,
            [household_income $250000+] BIT,
            [household_size] INT,
            [home_owner] BIT,
            [networth less than $50000] BIT,
            [networth $50000 - $99999] BIT,
            [networth $100000 - $249999] BIT,
            [networth $250000 - $499999] BIT,
            [networth $500000+] BIT,
            [presence_of_children] BIT,
            [presence_of_single_adult] BIT,
            [presence_of_young_adult] BIT,
            [presence_of_senior_adult] BIT,
            [presence_of_veteran] BIT,
            [estimated_age 18-24] BIT,
            [estimated_age 25-29] BIT,
            [estimated_age 30-34] BIT,
            [estimated_age 35-39] BIT,
            [estimated_age 40-44] BIT,
            [estimated_age 45-49] BIT,
            [estimated_age 50-54] BIT,
            [estimated_age 55-59] BIT,
            [estimated_age 60-64] BIT,
            [estimated_age 65-69] BIT,
            [estimated_age 70+] BIT,
            [buyer_men_apparel] BIT,
            [buyer_big_and_tall_men_apparel] BIT,
            [buyer_women_apparel] BIT,
            [buyer_petite_women_apparel] BIT,
            [buyer_plus_women_apparel] BIT,
            [buyer_young_women_apparel] BIT,
            [buyer_audio_books_and_music] BIT,
            [buyer_auto] BIT,
            [buyer_cosmetic_products] BIT,
            [buyer_books_and_magazines] BIT,
            [buyer_children_products] BIT,
            [buyer_gardening_products] BIT,
            [buyer_health_and_beauty_products] BIT,
            [buyer_hunting_and_shooting] BIT,
            [buyer_jewelry] BIT,
            [buyer_photography] BIT,
            [buyer_sports] BIT,
            [interest_arts] BIT,
            [interest_arts_antiques] BIT,
            [interest_auto] BIT,
            [interest_collector] BIT,
            [interest_board_games] BIT,
            [interest_sailing] BIT,
            [interest_camping] BIT,
            [interest_cat] BIT,
            [interest_children] BIT,
            [interest_antiques] BIT,
            [interest_coins] BIT,
            [interest_collectibles] BIT,
            [interest_military] BIT,
            [interest_sports] BIT,
            [interest_stamps] BIT,
            [interest_art_collectibles] BIT,
            [interest_cooking] BIT,
            [interest_gourmet_cooking] BIT,
            [interest_crafts] BIT,
            [interest_cruise] BIT,
            [interest_diet] BIT,
            [interest_dog] BIT,
            [interest_domestic_travel] BIT,
            [interest_education] BIT,
            [interest_aerobic] BIT,
            [interest_running] BIT,
            [interest_walking] BIT,
            [interest_fishing] BIT,
            [interest_food_wines] BIT,
            [interest_gambling] BIT,
            [interest_golf] BIT,
            [interest_health_medical] BIT,
            [interest_home_gardening] BIT,
            [interest_home_furnishings] BIT,
            [interest_home_improvement] BIT,
            [interest_hunting] BIT,
            [interest_grandchildren] BIT,
            [interest_parenting] BIT,
            [interest_pets] BIT,
            [interest_international_travel] BIT,
            [interest_equestrian] BIT,
            [interest_motorcycling] BIT,
            [interest_musical_instruments] BIT,
            [interest_nascar] BIT,
            [interest_natural_foods] BIT,
            [interest_photography] BIT,
            [interest_scuba_diving] BIT,
            [interest_self_improvement] BIT,
            [interest_snow_skiing] BIT,
            [interest_tennis] BIT,
            [interest_travel] BIT,
            [interest_woodworking] BIT,
            [reading_audio_books] BIT,
            [reading_current_affairs] BIT,
            [reading_financial] BIT,
            [reading_history] BIT,
            [reading_magazines] BIT,
            [reading_general] BIT,
            [reading_religious] BIT,
            [reading_space] BIT,
            [reading_science_fiction] BIT,
            [reading_religious_material] BIT,
            [entertain_gaming] BIT,
            [entertain_dvds] BIT,
            [entertain_tv_movies] BIT,
            [entertain_computers] BIT,
            [entertain_pc_games] BIT,
            [entertain_music_home_stereo] BIT,
            [entertain_music_player] BIT,
            [entertain_music_listener] BIT,
            [entertain_movies] BIT,
            [entertain_tv] BIT,
            [entertain_videos_games] BIT,
            [entertain_satellite] BIT,
            [entertain_theater] BIT,
            [entertain_music] BIT,
            [donor_contribution] BIT,
            [donor_animal] BIT,
            [donor_arts] BIT,
            [donor_children] BIT,
            [donor_wildlife] BIT,
            [donor_environment] BIT,
            [donor_health] BIT,
            [donor_international_aid] BIT,
            [donor_community] BIT,
            [donor_religious] BIT,
            [donor_veteran] BIT,
            [spectator_auto] BIT,
            [spectator_sports_tv] BIT,
            [spectator_football] BIT,
            [spectator_baseball] BIT,
            [spectator_basketball] BIT,
            [spectator_hockey] BIT,
            [spectator_soccer] BIT,
            [ethnicity_algerian] BIT,
            [ehtnicity_angolan] BIT,
            [ethnicity_black_african] BIT,
            [ethnicity_botswanian] BIT,
            [ethnicity_burkina_faso] BIT,
            [ethnicity_cameroonian] BIT,
            [ethnicity_central_african_republic] BIT,
            [ethnicity_chadian] BIT,
            [ethnicity_congolese] BIT,
            [ethnicity_ethiopian] BIT,
            [ethnicity_gabon] BIT,
            [ethnicity_gambian] BIT,
            [ethnicity_ghanaian] BIT,
            [ethnicity_guinean] BIT,
            [ehtnicity_hausa] BIT,
            [ethnicity_ivorian] BIT,
            [ethnicity_kenyan] BIT,
            [ethnicity_liberian] BIT,
            [ethnicity_libyan] BIT,
            [ethnicity_madagascan] BIT,
            [ethnicity_mozambican] BIT,
            [ethnicity_moroccan] BIT,
            [ethnicity_nigerian] BIT,
            [ethnicity_rwandan] BIT,
            [ethnicity_senegalese] BIT,
            [ethnicity_sierre_leone] BIT,
            [ethnicity_somalain] BIT,
            [ethnicity_sudanese] BIT,
            [ethnicity_swaziland] BIT,
            [ethnicity_ugandan] BIT,
            [ethnicity_zairean] BIT,
            [ethnicity_zambian] BIT,
            [ethnicity_zimbabwean] BIT,
            [ethnicity_zulu] BIT,
            [ethnicity_african_american] BIT,
            [ethnicity_caribbean_african_american] BIT,
            [ethnicity_american_indian] BIT,
            [ethnicity_bangladesh] BIT,
            [ethnicity_chinese] BIT,
            [ethnicity_korean] BIT,
            [ethnicity_japanese] BIT,
            [ethnicity_myanmar] BIT,
            [ethnicity_pakistani] BIT,
            [ethnicity_philippine] BIT,
            [ethnicity_thai] BIT,
            [ethnicity_tibetan] BIT,
            [ethnicity_vietnamese] BIT,
            [ethnicity_other_asian] BIT,
            [ethnicity_albanian] BIT,
            [ethnicity_austrian] BIT,
            [ethnicity_basque] BIT,
            [ethnicity_belgian] BIT,
            [ethnicity_belorussian] BIT,
            [ethnicity_bulgarian] BIT,
            [ethnicity_croatian] BIT,
            [ethnicity_czech] BIT,
            [ethnicity_danish] BIT,
            [ethnicity_dutch] BIT,
            [ethnicity_estonian] BIT,
            [ethnicity_finnish] BIT,
            [ethnicity_french] BIT,
            [ethnicity_georgian] BIT,
            [ethnicity_german] BIT,
            [ethnicity_greek] BIT,
            [ethnicity_hungarian] BIT,
            [ethnicity_italian] BIT,
            [ethnicity_latvian] BIT,
            [ethnicity_lithuanian] BIT,
            [ethnicity_luxembourgian] BIT,
            [ethnicity_polish] BIT,
            [ethnicity_portuguese] BIT,
            [ethnicity_romanian] BIT,
            [ethnicity_russian] BIT,
            [ethnicity_serbian] BIT,
            [ethnicity_swedish] BIT,
            [ethnicity_swiss] BIT,
            [ehtnicity_ukrainian] BIT,
            [ethnicity_maltese] BIT,
            [ethnicity_english] BIT,
            [ethnicity_irish] BIT,
            [ethnicity_welsh] BIT,
            [ethnicity_scottish] BIT,
            [ethnicity_hispanic] BIT,
            [ethnicity_arabic] BIT,
            [ethnicity_armenian] BIT,
            [ethnicity_afghan] BIT,
            [ethnicity_azerbaijani] BIT,
            [ethnicity_egyptian] BIT,
            [ethnicity_iraqi] BIT,
            [ethnicity_kazakhstan] BIT,
            [ethnicity_kirghizia] BIT,
            [ethnicity_kurdish] BIT,
            [ethnicity_kuwaiti] BIT,
            [ethnicity_persian] BIT,
            [ethnicity_qatari] BIT,
            [ethnicity_saudi] BIT,
            [ethnicity_turkish] BIT,
            [ethnicity_bosnian_muslim] BIT,
            [ethnicity_hindu] BIT,
            [ethnicity_jewish] BIT,
            [ethnicity_australian] BIT,
            [ethnicity_hawaiian] BIT,
            [ethnicity_indonesian] BIT,
            [ethnicity_maldivian_tongan] BIT,
            [ethnicity_new_zealand] BIT,
            [ethnicity_papua_new_guinean] BIT,
            [ethnicity_seychelles] BIT,
            [ethnicity_sinhalese_sri_lankan] BIT,
            [ethnicity_western_samoan] BIT,
            [home_value under $50000] BIT,
            [home_value $50000 - $99999] BIT,
            [home_value $100000 - $149999] BIT,
            [home_value $150000 - $199999] BIT,
            [home_value $200000 - $249999] BIT,
            [home_value $250000 - $299999] BIT,
            [home_value $300000 - $349999] BIT,
            [home_value $350000 - $399999] BIT,
            [home_value $400000 - $449999] BIT,
            [home_value $450000 - $499999] BIT,
            [home_value $500000 - $749999] BIT,
            [home_value $750000 - $999999] BIT,
            [home_value $1 million+] BIT,
            [mortgage community development authority] BIT,
            [mortgage conventional] BIT,
            [mortgage fha] BIT,
            [mortgage private party leader] BIT,
            [mortgage small business administration] BIT,
            [mortgage va] BIT,
            [mortgage wrap-around mortgage] BIT,
            [has_credit] BIT,
            [credit_card_gas] BIT,
            [credit_card_high_limit] BIT,
            [credit_card_standard] BIT,
            [credit_card_rewards] BIT,
            [occupation doctor] BIT,
            [occupation farming/agriculture] BIT,
            [occupation financial services] BIT,
            [occupation middle_management] BIT,
            [occupation office_clerical] BIT,
            [occupation professional/technical] BIT,
            [occupation retired] BIT,
            [occupation sales/marketing] BIT,
            [occupation skilled_trade] BIT,
            [occupation student] BIT,
            [occupation teacher/educator] BIT,
            [occupation accountant] BIT,
            [occupation business_owner] BIT,
            [occupation contractor] BIT,
            [occupation self_employed] BIT
        ) AS [data]
    """